// <auto-generated />
namespace PostOfiice.DAta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class deleteColumnQuantity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deleteColumnQuantity));
        
        string IMigrationMetadata.Id
        {
            get { return "201707271503469_deleteColumnQuantity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
