// <auto-generated />
namespace PostOfiice.DAta.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MainServiceGroupsTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MainServiceGroupsTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201705140516056_MainServiceGroupsTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
